
import { ProductType } from "./types";

// Enhanced featured products data with more details
export const featuredProducts: ProductType[] = [
  {
    id: 1,
    name: "Premium Organic Rice",
    description: "Farm-fresh rice grown with organic practices",
    price: 45,
    originalPrice: 60,
    rating: 4.8,
    reviews: 124,
    image: "https://images.unsplash.com/photo-1536304929831-ee1ca9d44906?q=80&w=800&auto=format&fit=crop",
    category: "grains",
    vendor: "Green Earth Farms",
    location: "Bhavnagar, Gujarat",
    stock: 250,
    isNew: false,
    isFeatured: true,
    discount: 25,
    tags: ["organic", "pesticide-free"]
  },
  {
    id: 2,
    name: "Fresh Tomatoes",
    description: "Juicy, locally grown vine-ripened tomatoes",
    price: 35,
    originalPrice: 42,
    rating: 4.7,
    reviews: 89,
    image: "https://images.unsplash.com/photo-1592924357228-91a4daadcfea?q=80&w=800&auto=format&fit=crop",
    category: "vegetables",
    vendor: "Valley Fresh Produce",
    location: "Nashik, Maharashtra",
    stock: 78,
    isNew: true,
    isFeatured: true,
    discount: 17,
    tags: ["fresh", "local"]
  },
  {
    id: 3,
    name: "Organic Spinach",
    description: "Nutrient-rich leafy greens from pesticide-free farms",
    price: 19,
    originalPrice: 24,
    rating: 4.9,
    reviews: 56,
    image: "https://images.unsplash.com/photo-1576045057995-568f588f82fb?q=80&w=800&auto=format&fit=crop",
    category: "vegetables",
    vendor: "Health Greens Co-op",
    location: "Pune, Maharashtra",
    stock: 45,
    isNew: false,
    isFeatured: true,
    discount: 21,
    tags: ["organic", "chemical-free"]
  },
  {
    id: 4,
    name: "Fresh Mangoes",
    description: "Sweet and ripe mangoes from local orchards",
    price: 80,
    originalPrice: 100,
    rating: 4.8,
    reviews: 210,
    image: "https://images.unsplash.com/photo-1553279768-865429fa0078?q=80&w=800&auto=format&fit=crop",
    category: "fruits",
    vendor: "Tropical Delights",
    location: "Ratnagiri, Maharashtra",
    stock: 120,
    isNew: false,
    isFeatured: true,
    discount: 20,
    tags: ["seasonal", "premium"]
  },
  {
    id: 5,
    name: "Ripe Bananas",
    description: "Farm-fresh ripe bananas, perfect for smoothies",
    price: 40,
    originalPrice: 45,
    rating: 4.6,
    reviews: 78,
    image: "https://images.unsplash.com/photo-1603833665858-e61d17a86224?q=80&w=800&auto=format&fit=crop",
    category: "fruits",
    vendor: "Orchard Fresh",
    location: "Wayanad, Kerala",
    stock: 95,
    isNew: false,
    isFeatured: false,
    discount: 11,
    tags: ["ready-to-eat", "nutritious"]
  },
  {
    id: 6,
    name: "Bell Peppers Mix",
    description: "Colorful mix of red, yellow and green bell peppers",
    price: 60,
    originalPrice: 75,
    rating: 4.7,
    reviews: 42,
    image: "https://images.unsplash.com/photo-1563565375-f3fdfdbefa83?q=80&w=800&auto=format&fit=crop",
    category: "vegetables",
    vendor: "Rainbow Farms",
    location: "Shimla, Himachal Pradesh",
    stock: 34,
    isNew: true,
    isFeatured: true,
    discount: 20,
    tags: ["colorful", "fresh"]
  },
  {
    id: 7,
    name: "Fresh Apples",
    description: "Crisp and juicy apples from mountain orchards",
    price: 52,
    originalPrice: 60,
    rating: 4.9,
    reviews: 135,
    image: "https://images.unsplash.com/photo-1570913149827-d2ac84ab3f9a?q=80&w=800&auto=format&fit=crop",
    category: "fruits",
    vendor: "Hill Country Orchards",
    location: "Kinnaur, Himachal Pradesh",
    stock: 76,
    isNew: false,
    isFeatured: true,
    discount: 13,
    tags: ["vitamin-rich", "highland-grown"]
  },
  {
    id: 8,
    name: "Organic Potatoes",
    description: "Organically grown potatoes, perfect for cooking",
    price: 18,
    originalPrice: 24,
    rating: 4.5,
    reviews: 68,
    image: "https://images.unsplash.com/photo-1518977676601-b53f82aba655?q=80&w=800&auto=format&fit=crop",
    category: "vegetables",
    vendor: "Earth Harvest",
    location: "Deesa, Gujarat",
    stock: 200,
    isNew: false,
    isFeatured: true,
    discount: 25,
    tags: ["organic", "versatile"]
  },
  {
    id: 9,
    name: "Fresh Oranges",
    description: "Sweet and juicy oranges packed with vitamin C",
    price: 22,
    originalPrice: 30,
    rating: 4.6,
    reviews: 94,
    image: "https://images.unsplash.com/photo-1582979512210-99b6a53386f9?q=80&w=800&auto=format&fit=crop",
    category: "fruits",
    vendor: "Citrus Valley",
    location: "Nagpur, Maharashtra",
    stock: 150,
    isNew: true,
    isFeatured: true,
    discount: 27,
    tags: ["vitamin-rich", "sweet"]
  }
];
