// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qwlnphitltwgkiujcqpm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF3bG5waGl0bHR3Z2tpdWpjcXBtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk3MTU5MTgsImV4cCI6MjA1NTI5MTkxOH0.cgUy4CtBdXUHW4JlA6Ns8bXXgFauI9jk9iZUkTtbSr4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);